# .streamlit/secrets.toml
[gcp_service_account]
type = "service_account"
project_id = "sistema-conferencia-danfe"
private_key_id = "6b6e2566e8bd32fb50d3ba48e7cc5aa02b301c0a"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8EYyfO7ORVz4f
isPOW/T8JPnO+VWOEE4U9O6WJIIyUaExcvQrwVj9bshHPc2dvNgDwquQdkPFRM1W
vdsGR4ifHpxcrcO/oAhbgvk2QhuvTx8wpnTTL3HwUDSiwUrQMtoFezyVieVxym4S
wd5kCddhzFImIoQ6tBepPbf3KxvT3MNNWdn2ZOSE6WZ4x0blVAoRCNf4nfEi08y7
ka4ww5LgGQynJ4xXGgq65IWj2PoEj4QFG0INOlHFkk/dDhQXZz9C17ozyEK4l1yx
roKUU1fp7WuL/WH7msLYKOjH2VhgqyXENxa2+kXk9zRhvTA48zaf6rmguND7kOmK
p4mJFyjhAgMBAAECggEAM/jpkouOGSkx6sePSvTQo+mX+2GeCg9pdJMnZ+iY7kzu
rdqlrX3WGNtHj6B9tQyd6ZQfk2GLYvWbhVAcOgUEtWxhK599i/QuuxNbyWnFetHz
vZ8Sg9YFt7KCiUO/Z//VjlQ7LtwXwzV868QVsDGkCsvLG+zH++0O6N88epq4KvjK
GWQc07aD5jztlwfpaRcIPT7G+DaA5GmXE/0VMVsw3maa6eQqjsQxvcxnBoPnd1Un
Xddn6qMCDu4Dm0oEkJZVCsWojYDz0S9ckusdfZZ3uPedM79AoTMKkUbu6O3ATnDY
YEDYr2snJtTVHpQxJNQ5kBqCtU0H+zGXLyGEcwaX/QKBgQD1hjHwBmuRcMm4DLoU
Ry0xcBYrOYxBhLFtSJRFfGDYoRk9KYGWTP70h7piTmd/DPpbS7SouITe0pyw+wNp
XOTft9VTjGiLqTWk0FyTE5s2iYMp/PxSsfa5kONEqUIX+8jiwv9qQJBgFylgVcZa
GFzQ12/hSokTSyIoH/MCGbMX1wKBgQDEF8d+2kkxbTDxUumOmDVxbLuaAOAObDdw
9+2ExUknblhR3ZTvpsEGbNyjU+6MLiY7PcAiQa8e7gDwxvbWZbbrIA27ky6QHbZO
TSzIaNFFspPPjeUqeiSOMzF0HmlvvmnDUkdkiiYDWK5g5ZGpYBrvvJO9U8XoZvNW
RuthBcJOBwKBgQDZfYRjAOzsqyKlXPDA4cQQ1R9uLs4lg6vACNj/LIyFmT9IRKo8
P/xhFJJwXs+jZhWoJcnk438f+3pINDLzdIxx+OCJ4AkEHmIcm05GIsoNZ4a+/RFv
F6JdAxGvUtfvcuSiquWic4rw89N9OL46NPaTMSQ0R9hhNN8O+C5FoApbhQKBgB7t
5UCD66GJKHwX6NDd/yf5z4lV9AEyXnhKEsOrXoOCqxmWiqRWOAHsb8yvM2QW717O
uZxtodKOFcXkjBB7EKP7dU8Nwv1mQlgNYi/mIIQOy7OkHO5bP6LSPk2jclv2u7Xc
J3ibNa23ciHEc/o0N2ty4hatvPyQKHeGTiAKiYBHAoGBAKRUfubNeRkvJtdgfjV8
qVEP77zzwnjWIX2og3cPNnAI2eQB8n70lFmLammqe+UrdZixPBmH5QKAKrNUK3XU
lmU3cnZRnBDbLrYStwY7KWtBCu7BVZFMjA/LZzSYOA3lqVcsQPapqrrCAuZhx4Jx
5ZFYeVz0TzGOw19fBWfIz5au
-----END PRIVATE KEY-----
"""
client_email = "sistema-conferencia-danfe@sistema-conferencia-danfe.iam.gserviceaccount.com"
client_id = "106514859279669420695"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sistema-conferencia-danfe%40sistema-conferencia-danfe.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# ID da planilha (extra√≠do da URL)
spreadsheet_id = "1n0zMI7hO6q5ZDHHK-BkCoMTNdyUUqbl8bwMUYk7Jaj4"
